### ISSUE TITLE
altering podfile after installing 25519 pod results in unresolveable error

### ISSUE THREAD

**Issue by abcdev** [FredericJacobs/25519#4]
steps to reproduce:

1 . open test project (e.g. ios single view app)
2 . add a podfile like this 

>platform :ios
>pod '25519'

3 . open *.xcworkspace and build ... everything is fine
4 . alter podfile to look like this

>platform :ios
>pod '25519'
>pod 'AFNetworking'

5 . pod install leads to (this error + unusable *.xcworkspace)

### Stack

```
   CocoaPods : 0.35.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.2 (14C109)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 403f6ccb21a75839b1790d03e65fca5b2d0e526b
```

### Plugins

```
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.4.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
platform :ios

pod '25519'
pod 'AFNetworking'
```

### Error

```
NoMethodError - undefined method `match' for 25519:Fixnum
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/dependency.rb:327:in `from_string'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/lockfile.rb:117:in `block in dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/lockfile.rb:116:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/lockfile.rb:116:in `dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/lockfile.rb:260:in `detect_changes_with_podfile'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:154:in `block in generate_podfile_state'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:153:in `generate_podfile_state'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:53:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:184:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by FredericJacobs** [comment]
It looks like it's a CocoaPods parsing issue? Not related to curve 25519.

Looks like it's looking for a version number?
